#!/usr/bin/env python3

from tkinter import *
from tkinter import filedialog
import read_csv


class Windows:

    def __init__(self, master = None):
        frame = Frame()
        frame.pack()

        self.printButton = Button(frame, text="Create Report", command=self.execute_report)
        self.printButton.pack(side=LEFT)

        self.quitButton = Button(frame, text="Quit", command=frame.quit)
        self.quitButton.pack(side=LEFT)


    def execute_report(self):
        self.read_csv(filename)

filename = filedialog.askopenfilename()

root = Tk()
b = Windows(root)
root.mainloop()