#!/usr/bin/env python3

from tkinter import *
import read_csv

requested_file = 0

def callback():
    requested_file = askopenfilename()
    return requested_file
    

class BuckysButtons:

    def __init__(self, master):
        frame = Frame(master)
        frame.pack()

        self.printButton = Button(frame, text="Create Report", command=self.execute_report)
        self.printButton.pack(side=LEFT)

        self.quitButton = Button(frame, text="Quit", command=frame.quit)
        self.quitButton.pack(side=LEFT)

        errmsg = 'Error!'
        self.openButton(text='File Open', command=callback).pack(fill=X)

    def execute_report(self):
        self.read_csv(requested_file)


root = Tk()
b = BuckysButtons(root)
root.mainloop()